### PR TITLE
Expand options for outputting context

### PR DESCRIPTION
**Pull request by Repiteo**
Bringing over this QOL from the [Pikmin 2 repo](https://github.com/projectPiki/pikmin2/pull/192). Context files now have these expanded capabilities:
- Can now be integrated into the buildsystem directly, allowing autogeneration of context for each individual file
- Define to ninja as implicitly created, so context can be swiftly removed via `ninja -t cleandead` if desired
- Given a dedicated file extension, both for ease of browsing in file explorer & to entirely remove from VSCode inspector

image

### CODE REVIEW

**Comment by Repiteo** [comment]
Testing locally on some of the repos that use this repo's formatting, and this doesn't seem to work as expected compared to Pikmin 2. Gonna try to get to the bottom of that

**Review by ribbanya — CHANGES_REQUESTED** [review]
Would recommend swapping the extension to `.ctx.cpp` so that editors and file managers can understand that it is still C++ code. I see that you updated the VS Code settings but this is not nearly sufficient in my opinion.

I suppose doing that would make it harder to do bulk operations on source files, as you'd have to either explicitly exclude `*.ctx.cpp` or use something like `git ls-files`, but ultimately I think preserving the extension would be preferable.

**Comment by encounter** [comment]
For the recent feature I added to objdiff, auto-creating a decomp.me scratch, I implemented this same thing but slightly differently. Mainly: context generation are separate rules, and always available, but not built by default. I can see why it's useful to generate all of them at once, so maybe I can implement a `ninja context` step to do so

**Comment by Repiteo** [comment]
@ribbanya Having tried the alternative locally, I disagree with swapping the extension. With this implementation, it's making context for *every compiled file*, so that bloat would add up extremely fast. Because excluding it explicitly isn't as straightforward as I'd like, and considering the main use-case is to be taken to `decomp.me`, I'm fine with leaving it as-is in a metadata-esque way

However, one alternative would be still compiling all the context, but in a designated location. It would output similar to how `.obj` files are created in their own folders in a way that mirrors the scripts being compiled, just in a separate location. Excluding an entire directory would be *significantly* easier than dealing with wildcards

**Comment by ribbanya** [comment]
Yeah that makes sense. In that case I would prefer a layout of `build/ctx/dolphin/gx/GXInit.c` mirroring the source tree. Maybe `build/ctx/src/...` if you want to allow for multiple context root directories.

**Comment by encounter** [comment]
Thanks for the work on this, closing because context generation and objdiff decomp.me integration is available on main.

**Pull request closed without merging**
